version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
